admin/views.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user
from models import User
from app import db, requires_roles
import json

# CONFIG
admin_blueprint = Blueprint('admin', __name__, template_folder='templates')


# ROUTES

# Displaying all users in the admin page.
@admin_blueprint.route('/admin', methods=['GET'])
@login_required
@requires_roles('admin')
def admin():
    return render_template('admin.html', current_users=User.query.all())


@admin_blueprint.route('/contact')
def contact():
    return render_template('contact.html')


@admin_blueprint.route('/terms')
def terms():
    return render_template('terms.html')


@login_required
@requires_roles('admin')
@admin_blueprint.route('/update', methods=['POST', 'GET'])
def update():
    return render_template('update.html')

calculator/views.py
# Imports
from flask import Blueprint, render_template


# Config
calculator_blueprint = Blueprint('calculator', __name__, template_folder='templates')


@calculator_blueprint.route('/calculator')
def calculator():
    return render_template('calculator.html')


@calculator_blueprint.route('/<int:id>/update', methods=('GET', 'POST'))
def update(id):
    return render_template('update.html')


@calculator_blueprint.route('/<int:id>/delete')
def delete(id):

    return calculator()

users/views.py
import logging
from datetime import datetime

import flask
from flask import Blueprint, render_template, flash, redirect, url_for, session, request
from flask_login import login_user, logout_user, current_user
from werkzeug.security import check_password_hash
from app import db
from flask_login import login_required
from models import User
from users.forms import RegisterForm, LoginForm

users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():

        user = User.query.filter_by(username=form.username.data).first()

        if user:
            flash('Username already exists', "danger")
            return render_template('register.html', form=form)

        new_user = User(
            firstname=form.firstname.data,
            lastname=form.lastname.data,
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
            role='user')

        db.session.add(new_user)
        db.session.commit()

        # Send new user registered notification to security log file
        logging.warning('SECURITY - User registration [%s, %s]', form.email.data, request.remote_addr)

        # Sends user to login page and displays a message that a user has been created.
        return redirect(url_for('users.login')), flash('The user ' + new_user.email + ' has been created!', "success")

    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    # if session attribute logins does not exist create attribute logins
    if not session.get('logins'):
        session['logins'] = 0
    # if login attempts is 3 or more create an error message
    elif session.get('logins') >= 3:
        flash('Number of incorrect logins exceeded', "warning")

    form = LoginForm()

    if form.validate_on_submit():

        # increase login attempts by 1
        session['logins'] += 1

        user = User.query.filter_by(username=form.username.data).first()

        if not user or not check_password_hash(user.password, form.password.data):
            # if no match create appropriate error message based on login attempts
            if session['logins'] == 3:
                flash('Number of incorrect logins exceeded', "warning")
            elif session['logins'] == 2:
                flash('Please check your login details and try again. 1 login attempt remaining', "warning")
            else:
                flash('Please check your login details and try again. 2 login attempts remaining', "warning")

                # Send Invalid log in attempt notification to security log file
                logging.warning('SECURITY - Invalid log in attempt [%s, %s]', form.username.data, request.remote_addr)

            return render_template('login.html', form=form)

        session['logins'] = 0

        login_user(user)

        db.session.commit()

        # Send Log in notification to security log file
        logging.warning('SECURITY - Log in [%s, %s, %s]', current_user.id, current_user.email, request.remote_addr)

        # direct to role appropriate page
        if current_user.role == 'admin':
            return redirect(url_for('users.profile'))
        else:
            return redirect(url_for('users.profile'))

    return render_template('login.html', form=form)


@users_blueprint.route('/logout')
def logout():
    # Send Log out notification to security log file
    logging.warning('SECURITY - Log out [%s, %s, %s]', current_user.id, current_user.email, request.remote_addr)

    logout_user()
    return redirect(url_for('index'))


# View user profile
@users_blueprint.route('/profile')
@login_required
def profile():
    return render_template('profile.html')


# View user's panel
@users_blueprint.route('/panel')
@login_required
def panel():
    return render_template('panel.html')

templates/503.html
{% extends "base.html" %}

{% block content %}
    {# Unavailable Service Page #}
    <h1 class="title is-1">503</h1>
    <h2 class="title is-2">Service Unavailable</h2>

{% endblock %}

templates/admin.html
{% extends "base.html" %}

{% block content %}

    {% if current_user.is_authenticated and current_user.role=='admin' %}
        <ul style="justify-content: center" class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="viewusers-tab" data-bs-toggle="tab" data-bs-target="#viewusers" type="button" role="tab" aria-controls="viewusers" aria-selected="true">View All Users</button>
                </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="viewlogs-tab" data-bs-toggle="tab" data-bs-target="#viewlogs" type="button" role="tab" aria-controls="viewlogs" aria-selected="false">View Security Logs</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="quiz-tab" data-bs-toggle="tab" data-bs-target="#quiz" type="button" role="tab" aria-controls="quiz" aria-selected="false">Quiz Questions</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="leadrbrd-tab" data-bs-toggle="tab" data-bs-target="#leaderboard" type="button" role="tab" aria-controls="leaderboard" aria-selected="false">Leaderboard</button>
            </li>

        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="viewusers" role="tabpanel" aria-labelledby="viewusers-tab">
                <table style="margin-top: 50px" class="table table-hover">
                      <thead>
                        <tr>
                          <th scope="col">ID</th>
                          <th scope="col">First Name</th>
                          <th scope="col">Last Name</th>
                          <th scope="col">Username</th>
                          <th scope="col">Email</th>
                          <th scope="col">Role</th>
                          <th style="text-align: center; " scope="col">Tools</th>

                        </tr>
                      </thead>
                      <tbody>
                        {% for user in current_users %}
                            <tr>
                                <th scope="row">{{ user.id }}</th>
                                <td>{{ user.firstname }}</td>
                                <td>{{ user.lastname }}</td>
                                <td>{{ user.username }}</td>
                                <td>{{ user.email }}</td>
                                <td>{{ user.role }}</td>
                                <td style="text-align: center;">
                                    <button class="btn btn-success">Update</button>
                                    <button class="btn btn-danger">Delete</button>
                                </td>

                            </tr>
                        {% endfor %}
                      </tbody>
                </table>
            </div>

            <div  class="tab-pane fade" id="viewlogs" role="tabpanel" aria-labelledby="viewlogs-tab">

            </div>

            <div class="tab-pane fade" id="quiz" role="tabpanel" aria-labelledby="quiz-tab">
                sdfsdfhhhh
            </div>

            <div class="tab-pane fade" id="leaderboard" role="tabpanel" aria-labelledby="leaderboard-tab">
                ghjghjghjkkkkk
            </div>

        </div>
    {% endif %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Carbon Tracer</title>
    <link rel="shortcut icon" href="../static/img/logo.svg" />
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="/static/css/base.css" rel="stylesheet">

    <!-- Kit for Icons-->
    <script src="https://kit.fontawesome.com/45463fbacb.js" crossorigin="anonymous"></script>
    <script type='text/javascript' src="https://www.gstatic.com/charts/loader.js"></script>

    <!-- Javascript Scripts -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="../static/js/geochart.js"></script>
    <script type="text/javascript" src="../static/js/linechart.js"></script>


  </head>

  <body class="d-flex flex-column min-vh-100">

    <!-- Begin page content -->
    <main class="flex-shrink-0">

        <!-- Navigation Bar -->
        <div class="container py-2">

            <div class="d-flex flex-column flex-md-row align-items-center pb-2 mb-1 border-bottom mr-auto">

                <!-- Logo and Text -->
                <a href="/" id="title" class="d-flex align-items-center text-dark text-decoration-none">
	                <img src="/static/img/logo.svg" alt="Carbon Tracer logo" height="40px"/>
                    <span style="text-decoration: none; font-family: Helvetica Now Display, sans-serif; font-weight: Bold; color: #37323e" class="fs-1"> &nbspCarbon Tracer</span>
                </a>

                <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">

                    <!-- Content for logged in users -->
                    {% if current_user.role == 'user' %}

                        <a class="me-3 py-2 nav-link" href="{{ url_for('index') }}" id="navlink">Home</a>
                        <a class="me-3 py-2 nav-link" href="{{ url_for('users.panel') }}" id="navlink">My Panel</a>
                        <a class="me-3 py-2 nav-link" href="{{ url_for('calculator.calculator') }}" id="navlink">Calculator</a>
                        <a class="me-3 py-2 nav-link" href="{{ url_for('test.test') }}" id="navlink">Test</a>
                        <a class="me-3 py-2 nav-link" href="{{ url_for('admin.contact') }}" id="navlink">Contact</a>
                    {% endif %}

                    {% if  current_user.role == 'admin' %}

                        <a class="me-3 py-2 nav-link" href="{{ url_for('admin.admin') }}" id="navlink">Admin's Panel</a>

                    {% endif %}

                    <!-- General content of the authenticated users -->
                    {% if current_user.is_authenticated %}

                        <div class="dropdown dropdown-menu-end">
                            <a type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown">
                                <img src="../static/img/users/{{ current_user.username }}.jpg" alt="" width="32" height="32" class="rounded-circle me-2">
                                <strong>{{ current_user.firstname }}</strong>
                            </a>
                            <ul class="dropdown-menu mx-0 shadow" style="width: 220px;">

                                <li>
                                    <a class="dropdown-item d-flex gap-2 align-items-center" href="{{ url_for('users.profile') }}">
                                        <i class="fas fa-user"></i> Profile
                                    </a>
                                </li>
                                {% if current_user.role == 'admin' %}
                                    <li><hr class="dropdown-divider"></li>

                                    <li>
                                        <a class="dropdown-item d-flex gap-2 align-items-center" href="{{ url_for('calculator.calculator') }}">
                                            <i class="fas fa-calculator"></i> Calculator
                                        </a>
                                    </li>

                                    <li>
                                        <a class="dropdown-item d-flex gap-2 align-items-center" href="{{ url_for('test.test') }}">
                                            <i class="fas fa-question"></i> Test
                                        </a>
                                    </li>


                                {% endif %}
                                <li><hr class="dropdown-divider"></li>

                                <li>
                                    <a class="dropdown-item dropdown-item-danger d-flex gap-2 align-items-center" href="{{ url_for('users.logout') }}">
                                        <i class="fas fa-sign-out-alt"></i> Sign Out
                                    </a>
                                </li>

                            </ul>

                        </div>

                    {% endif %}

                    <!-- What visitors can see on the website -->
                    {% if not current_user.is_authenticated %}

                        <a class="me-3 py-2 nav-link" href="{{ url_for('index') }}" id="navlink">Home</a>
                        <a class="me-3 py-2 nav-link" href="{{ url_for('calculator.calculator') }}" id="navlink">Calculator</a>
                        <a class="me-3 py-2 nav-link" href="{{ url_for('test.test') }}" id="navlink">Test</a>
                        <a class="me-3 py-2 nav-link" href="{{ url_for('admin.contact') }}" id="navlink">Contact</a>
                        <a style="margin-left: 10px" class="btn btn-primary" href="{{ url_for('users.register') }}" role="button">Sign Up</a>
                        <a style="margin-left: 10px" class="btn btn-success" href="{{ url_for('users.login') }}" role="button">Log In</a>

                    {% endif %}

                </nav>

            </div>

        </div>

        <!-- Here is where all the content from the extended pages -->  <!-- -->
        <div class="hero-body">
            <div class="container has-text-centered">
                {% block content %}

                {% endblock %}
            </div>
        </div>

    </main>

    <footer id="footer" style="margin-bottom: 0" class="footer mt-auto py-3 bg-transparent ">
      <div class="container text-center ">
        <div class="container border-top"></div>
        <span class="text-muted ">© 2021-2022 Carbon Tracer</span>
      </div>
    </footer>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>

templates/calculator.html
{% extends "base.html" %}

{% block content %}

    <h1>Calculator</h1>


{% endblock %}

templates/contact.html
{% extends "base.html" %}

{% block content %}
    <div class="row" >
        <div class="col-md-6 mb-4">
            <div style="font-size: 18px;">
                <h1>Project members</h1>
                <ul>
                    <li>Dimitris Poulimenos <a target="_blank" style="text-decoration: none" href="https://github.com/dpoulimen0s">GitHub</a></li>
                    <li>William Joseph Brook Newbould <a target="_blank1" style="text-decoration: none" href="https://github.com/WillNewbo12">GitHub</a></li>
                    <li>Jackson Thomas <a target="_blank2" style="text-decoration: none" href="https://github.com/jacky-ct">GitHub</a></li>
                    <li>Will Adams <a target="_blank3" style="text-decoration: none" href="https://github.com/c0039921">GitHub</a></li>
                    <li>Zhuolin Yong <a target="_blank4" style="text-decoration: none" href="https://github.com/b9067280">GitHub</a></li>
                </ul>
            </div>

            <div style="font-size: 18px;">
                <p style="margin-top: 80px;">You can send us an email: <a style="text-decoration: none;" href="mailto:carbontracer@gmail.com">carbontracer@gmail.com</a></p>
            </div>

        </div>

        <div class="col-md-6 mb-4">
            <div class="mapouter">
                <div class="gmap_canvas">
                    <iframe width="100%" height="300" id="gmap_canvas" src="https://maps.google.com/maps?q=Newcastle University&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                    <br>
                    <style>.gmap_canvas {overflow:hidden;background:none!important;height:400px;width:100%;}</style>
                </div>
            </div>
        </div>

    </div>
    <hr style="margin-top: -100px;">
    <!-- Contact Form -->
    <h3 class="mb-3 pb-2 pb-md-0 mb-md-5">Contact Us</h3>
    <form>
        <div class="row">
            <div class="col-md-6 mb-3 ">
                  <div class="form-floating mb-3">
                      <input type="text" class="form-control" id="floatingInput" placeholder="firstname" required>
                      <label for="floatingInput">First Name</label>
                  </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingInput" placeholder="lastname" required>
                    <label for="floatingInput">Last Name</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-4">
                  <div class="form-floating mb-3">
                      <input type="email" class="form-control" id="floatingInput" placeholder="email" required>
                      <label for="floatingInput">Email</label>
                  </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="form-floating">
                    <select class="form-select" id="floatingSelectGrid" aria-label="Floating label select example" required>
                        <option value="1">Visitor</option>
                        <option value="2">User</option>
                    </select>
                    <label for="floatingSelectGrid">Type</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-floating mb-3">
                <textarea class="form-control" placeholder="message" id="floatingInput" style="height: 100px" required></textarea>
                <label style="margin-left: 10px" for="floatingInput">Message</label>
            </div>
        </div>
        <div class="mt-4 pt-2">
            <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
        </div>
    </form>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div style="margin-bottom: 10px; top: 0;" class="d-flex flex-row-reverse py-0">
        <img class="langhov" src="../static/img/china.png" width="32" height="32" >
        <img class="langhov" style="margin-right: 5px" src="../static/img/german.png" width="32" height="32" >
        <img class="langhov" style="margin-right: 5px" class="flex-right" src="../static/img/united-kingdom.png" width="32" height="32" >
    </div>

    <div class="container py-3 jump1">
       <div class="jumbotron py-3 ">
            <div class="container py-3">
                  <h1 class="display-1">Welcome to Carbon Tracer</h1>
                  <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
                  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
            </div>
       </div>
    </div>
    <hr>
    <div  class="container marketing">
        <!-- Three columns of text below the carousel -->
        <div class="row">
          <div style="bottom: 0" class="col-lg-4">
            <i class="fas fa-crosshairs fa-10x"></i>
            <h2>Our Vision</h2>
            <p>Here we can explain what's the goal of this application.</p>
            <p><a class="btn btn-primary" href="#">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div style="bottom: 0" class="col-lg-4">
            <i class="fab fa-connectdevelop fa-10x"></i>
            <h2>Contribution</h2>
            <p>Here we can explain why users have to use and calculate their emission.</p>
            <p><a class="btn btn-primary" href="#">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div style="bottom: 0" class="col-lg-4">
            <i class="fas fa-chart-bar fa-10x"></i>
            <h2>Stats</h2>
            <p>Here we can give users a hint what stats stands for and what represent and redirect them to a stat page or something.</p>
            <p><a class="btn btn-primary" href="#">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
    </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}

  {# Register Page #}
  {% if not current_user.is_authenticated %}
  <div style="margin-top: -50px;" class="container">
      <div class="row justify-content-center align-items-center 0">
          <div class="col-12 col-lg-9 col-xl-7">
                <div class="card-body p-3 p-md-5">
                    <h3 class="mb-3 pb-2 pb-md-0 mb-md-5">Register</h3>
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                    <span> {{ message }} </span>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    <form method="POST">

                        <div class="row">
                            <div class="col-md-6 mb-4">
                                 <div class="field">
                                    {{ form.csrf_token() }}
                                    <div class="form-floating mb-3">
                                        {{ form.firstname(type="text", class="form-control", id="floatingInput", placeholder="firstname")}}
                                        {% for error in form.firstname.errors %}
                                            <div class="alert alert-danger" role="alert">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                        <label for="floatingInput">First Name</label>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 mb-4">
                                <div class="field">
                                    {{ form.csrf_token() }}
                                    <div class="form-floating mb-3">
                                        {{ form.lastname(type="text", class="form-control", id="floatingInput", placeholder="lastname")}}
                                            {% for error in form.lastname.errors %}
                                                <div class="alert alert-danger" role="alert">
                                                    {{ error }}
                                                </div>
                                            {% endfor %}
                                        <label for="floatingInput">Last Name</label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-4">
                                <div class="field">
                                    {{ form.csrf_token() }}
                                    <div class="form-floating mb-3">
                                        {{ form.username(type="text", class="form-control", id="floatingInput", placeholder="username")}}
                                            {% for error in form.username.errors %}
                                                <div class="alert alert-danger" role="alert">
                                                    {{ error }}
                                                </div>
                                            {% endfor %}
                                        <label for="floatingInput">Username</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="field">
                                    {{ form.csrf_token() }}
                                    <div class="form-floating mb-3">
                                        {{ form.email(type="email", class="form-control", id="floatingInput", placeholder="email")}}
                                        {% for error in form.email.errors %}
                                            <div class="alert alert-danger" role="alert">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                        <label for="floatingInput">Email</label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-4">
                                <div class="field">
                                    {{ form.csrf_token() }}
                                    <div class="form-floating mb-3">
                                        {{ form.password(type="password", class="form-control", id="floatingInput", placeholder="password")}}
                                        {% for error in form.password.errors %}
                                            <div class="alert alert-danger" role="alert">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                        <label for="floatingInput">Password</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="field">
                                    {{ form.csrf_token() }}
                                    <div class="form-floating mb-3">
                                        {{ form.confirm_password(type="password", class="form-control", id="floatingInput", placeholder="confirmpassword")}}
                                        {% for error in form.confirm_password.errors %}
                                            <div class="alert alert-danger" role="alert">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                        <label for="floatingInput">Confirm Password</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <input class="form-check-input text-non-decorated" type="checkbox" id="checkboxNoLabel" value="" aria-label="..." required>
                            <label class="text-non-decorated">By clicking submit you accept our <a href="{{ url_for('admin.terms') }}" class="text-decoration-none">Terms and Conditions</a> agreement.</label>
                        </div>
                        <div class="mt-4 pt-2">
                            {{ form.submit(class="btn btn-primary btn-lg") }}
                        </div>
                    </form>
                </div>
          </div>
      </div>
  </div>
  {% else %}
        <h3 class="title is-3">Only logged out users allowed to create a user</h3>
  {% endif %}
{% endblock %}

templates/update.html
{% extends "base.html" %}

{% block content %}

    {{ form.csrf_token() }}
    {{ form.title(class="input") }} {% for error in form.title.errors %} {{ error }} {% endfor %}
    {{ form.body(class="textarea") }} {% for error in form.body.errors %} {{ error }} {% endfor %}
    {{ form.submit(class="button is-info is-centered") }}

{% endblock %}